### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by jolamar** [ITDCD/uits-web-boilerplate#7]
If &lt;select multiple&gt; it should not have the background arrow or be set to a specific height. 

    select[multiple] {
      height: inherit;
      background: #fafafa;
    }

**Comment by jolamar** [comment]
I fixed that issue on master and uploaded new stylesheet to assets.uits.iu.edu

**Comment by levimcg** [comment]
@jolamar :boom: Yay! :boom:
